### ISSUE TITLE
image_adapter not found

### ISSUE THREAD

**Issue by dalmackay** [doloreshaze337/taggui#1]
![Screenshot 2024-08-27 230816](https://github.com/user-attachments/assets/88adf972-8697-493d-98e7-ea6a34c00757)
![Screenshot 2024-08-27 230751](https://github.com/user-attachments/assets/dc535106-9fcf-44c4-a429-c6cc05a5fe56)

I installed it before first launch. not found

**Comment by UnbelievableCat** [comment]
Try put joycaption in taggui folder like  F:\taggui\taggui\joycaption

**Comment by doloreshaze337** [comment]
Is this `taggui` folder the one with `run_gui.py` in it? If it is, you've put the `joycaption` folder in the wrong place. The `joycaption` folder needs to be at the root of the project, alongside the `clip-vit-base-patch32` folder and the `requirements.txt` file.

**Comment by UnbelievableCat** [comment]
> Is this `taggui` folder the one with `run_gui.py` in it? If it is, you've put the `joycaption` folder in the wrong place. The `joycaption` folder needs to be at the root of the project, alongside the `clip-vit-base-patch32` folder and the `requirements.txt` file.

I had the same error with `joycaption` folder in root of the project (as instruction suggested), but the error disappeared when I moved it inside `taggui` with `run_gui.py` script, don't know why but now it works fine. 
![image](https://github.com/user-attachments/assets/e554948c-7ca9-4fac-a5bd-e35839bcf9e3)
![image](https://github.com/user-attachments/assets/00e11fd0-0d17-4b72-bf1f-a877bfa03812)
![image](https://github.com/user-attachments/assets/cbda9ca4-dfa8-40f5-95e1-c2e5d05037bf)


New install with `joycaption` in root
![image](https://github.com/user-attachments/assets/3e363852-1c55-41be-bd9d-1e5ad787e870)

Loading unsloth/Meta-Llama-3.1-8B-bnb-4bit...
Traceback (most recent call last):
File "E:\taggui\taggui\auto_captioning\captioning_thread.py", line 145, in run
raise exception
File "E:\taggui\taggui\auto_captioning\captioning_thread.py", line 141, in run
self.run_captioning()
File "E:\taggui\taggui\auto_captioning\captioning_thread.py", line 89, in run_captioning
model.monkey_patch_after_loading()
File "E:\taggui\taggui\auto_captioning\models\joycaption.py", line 61, in monkey_patch_after_loading
self.image_adapter.load_state_dict(torch.load("joycaption/image_adapter.pt", map_location="cpu"))
^
^
File "E:\taggui\venv\Lib\site-packages\torch\serialization.py", line 998, in load
with _open_file_like(f, 'rb') as opened_file:
^
^
File "E:\taggui\venv\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
return _open_file(name_or_buffer, mode)
^
^
File "E:\taggui\venv\Lib\site-packages\torch\serialization.py", line 426, in __init__
super().__init__(open(name, mode))
^
^
FileNotFoundError
:
[Errno 2] No such file or directory: 'joycaption/image_adapter.pt'

Shouldn't it need to open `joycaption\image_adapter.pt` with `\` on Windows and not  `joycaption/image_adapter.pt` with `/` ?

**Comment by doloreshaze337** [comment]
Windows should support both types of paths, it just defaults to using backslashes. Regardless, it seems like it's a working directory problem. I normally start TagGUI from the root folder by running `python taggui\run_gui.py` via a launch script, which means that `joycaption/image_adapter.pt` points to the `joycaption` folder in the root folder. I've just tested running the `run_gui.py` script directly from the `taggui` folder and it indeed crashes with the `No such file or directory: 'joycaption/image_adapter.pt'` error, so I'm assuming both of you were trying to run the `run_gui.py` script directly. I can add a launch script to the root folder to start `run_gui.py` properly, if that helps. I didn't add one yet since I use Conda environments and didn't want to force Conda/venv on anybody.

**Comment by UnbelievableCat** [comment]
Oh, yes, you are absolutely right. Sorry for the distraction and thanks for your work.

**Comment by dalmackay** [comment]
Got it, thank you. I'm a noob who is used to .exe so I was just double clicking run.
